### ISSUE TITLE
SellOrders fails to find box with tokens

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/ergo-dex#9]
There is an unspent box with 900 tokens. 
```
seller (develop) ✔ java -jar ../ergotool-3.1.1.jar --conf ergo_tool_config.json dex:SellOrder storage 1000000000 "56cf33485be550cc32cf607255be8dc8c32522d0539f6f01d44028dc1d190450" 100 5000000
Storage password>
Creating prover...SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 Ok
Loading unspent boxes from at address 9fg9Nk1obG76BqRL5fpWwyNem2WCPXMpkH3RP184ePYKsm4ZqAC... Ok
java.lang.RuntimeException: Not enough tokens (id 56cf33485be550cc32cf607255be8dc8c32522d0539f6f01d44028dc1d190450) in boxes to pay 100, found only 0
	at org.ergoplatform.appkit.BoxOperations.selectTop(BoxOperations.java:56)
	at org.ergoplatform.appkit.ergotool.dex.CreateSellOrderCmd.$anonfun$runWithClient$4(CreateSellOrderCmd.scala:61)
	at org.ergoplatform.appkit.RestApiErgoClient.execute(RestApiErgoClient.java:42)
	at org.ergoplatform.appkit.ergotool.dex.CreateSellOrderCmd.runWithClient(CreateSellOrderCmd.scala:52)
	at org.ergoplatform.appkit.commands.RunWithErgoClient.run(Commands.scala:64)
	at org.ergoplatform.appkit.commands.RunWithErgoClient.run$(Commands.scala:62)
	at org.ergoplatform.appkit.ergotool.dex.CreateSellOrderCmd.run(CreateSellOrderCmd.scala:39)
	at org.ergoplatform.appkit.ergotool.ErgoTool$.run(ErgoTool.scala:50)
	at org.ergoplatform.appkit.ergotool.ErgoTool$.main(ErgoTool.scala:31)
	at org.ergoplatform.appkit.ergotool.ErgoTool.main(ErgoTool.scala)
Error executing command CreateSellOrderCmd(org.ergoplatform.appkit.config.ErgoToolConfig@5e671e20,dex:SellOrder,storage,org.ergoplatform.appkit.SecretString@50,1000000000,ErgoToken(56cf33485be550cc32cf607255be8dc8c32522d0539f6f01d44028dc1d190450, 100),5000000):
 java.lang.RuntimeException: Not enough tokens (id 56cf33485be550cc32cf607255be8dc8c32522d0539f6f01d44028dc1d190450) in boxes to pay 100, found only 0
```

**Comment by greenhat** [comment]
@aslesarenko Probably the proper way to resolve it is to do https://github.com/ergoplatform/ergo/issues/1029 and use it in appkit. I'm looking into it.

**Comment by greenhat** [comment]
It turned out that #15 is the cause. I'm closing it.
